AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: AWS CodeStar projectID used to associate new resources to team members
  Stage:
    Type: String
    Description: The name for a project pipeline stage, such as Staging or Prod, for which resources are provisioned and deployed.
    Default: 'dev'

Resources:
  FileUploadMgrHandler:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      Runtime: go1.x
      Timeout: 10
      Environment:
        Variables:
          JWT_SECRET: kqivVVuYGZRxsI8S14en
          TOKEN_EXPIRY_MIN: 60
          USERS_TABLE_NAME: !Ref UsersTable
          SESSIONS_TABLE_NAME: !Ref SessionsTable
      Role: arn:aws:iam::260345904678:role/DynamoDbBasedLambdaRole
      Events:
        PostGraphQlEvent:
          Type: Api
          Properties:
            Path: /graphql
            Method: post
        GetGraphQlEvent:
          Type: Api
          Properties:
            Path: /graphql
            Method: get
  UsersTable:
    Description: DynamoDB Table for storing user records
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${Stage}_users'
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      AttributeDefinitions:
        - AttributeName: 'email'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: "email"
          KeyType: "HASH"
  SessionsTable:
    Description: DynamoDB Table for storing file sessions for the uploads
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${Stage}_sessions'
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      AttributeDefinitions:
        - AttributeName: 'id'
          AttributeType: 'S'
        - AttributeName: 'email'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
        - AttributeName: "email"
          KeyType: "RANGE"